name: Release

on:
  release:
    types: [prereleased, edited]

jobs:
  build:
    name: Build GitHub action and AWS lambda function
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"

      - name: Install dependencies
        run: yarn install

      - name: Build GitHub action
        run: yarn build-action

      - name: Build lambda distribution
        run: yarn dist

      - name: Update package.json version
        run: |
          tmp=$(mktemp)
          jq '.version = "${{ github.ref }}"' package.json > "$tmp"
          mv "$tmp" package.json

      - name: Setup GitHub git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Push builds
        run: |
          git add package.json ping-slack/dist/index.js terraform/lambda.zip
          git commit -m "Build app for release"
          git push

      - name: Move release tag to latest commit
        run: |
          git tag --force "${{ github.ref }}" $(git rev-parse HEAD)
          git push --force --tags
