name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  action:
    name: Build GitHub action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build GitHub action
        run: yarn build-action

  build:
    name: Build lambda function
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build lambda distribution
        run: yarn dist

  test:
    name: Test lambda function
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test
